name: Valgrind

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkLeaks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt -y install valgrind gnuplot
    - name: Build from Make
      run: make -C 3_Implementation
    - name: cd to implementation
      run: cd ./3_Implementation
    - name: valgrind test
      run: pwd && valgrind --tool=memcheck ./folodesolver.out < ./../7_Other/runtimeIp.txt